/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as EducationsIndexRouteImport } from './routes/educations/index'
import { Route as CvsIndexRouteImport } from './routes/cvs/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as CvsCreateRouteImport } from './routes/cvs/create'
import { Route as CvsIdRouteImport } from './routes/cvs/$id'
import { Route as CvsIdEditRouteImport } from './routes/cvs/$id_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationsIndexRoute = EducationsIndexRouteImport.update({
  id: '/educations/',
  path: '/educations/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvsIndexRoute = CvsIndexRouteImport.update({
  id: '/cvs/',
  path: '/cvs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvsCreateRoute = CvsCreateRouteImport.update({
  id: '/cvs/create',
  path: '/cvs/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CvsIdRoute = CvsIdRouteImport.update({
  id: '/cvs/$id',
  path: '/cvs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CvsIdEditRoute = CvsIdEditRouteImport.update({
  id: '/cvs/$id_/edit',
  path: '/cvs/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cvs/$id': typeof CvsIdRoute
  '/cvs/create': typeof CvsCreateRoute
  '/companies/': typeof CompaniesIndexRoute
  '/cvs/': typeof CvsIndexRoute
  '/educations/': typeof EducationsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/cvs/$id/edit': typeof CvsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cvs/$id': typeof CvsIdRoute
  '/cvs/create': typeof CvsCreateRoute
  '/companies': typeof CompaniesIndexRoute
  '/cvs': typeof CvsIndexRoute
  '/educations': typeof EducationsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/cvs/$id/edit': typeof CvsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cvs/$id': typeof CvsIdRoute
  '/cvs/create': typeof CvsCreateRoute
  '/companies/': typeof CompaniesIndexRoute
  '/cvs/': typeof CvsIndexRoute
  '/educations/': typeof EducationsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/cvs/$id_/edit': typeof CvsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cvs/$id'
    | '/cvs/create'
    | '/companies/'
    | '/cvs/'
    | '/educations/'
    | '/projects/'
    | '/skills/'
    | '/cvs/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cvs/$id'
    | '/cvs/create'
    | '/companies'
    | '/cvs'
    | '/educations'
    | '/projects'
    | '/skills'
    | '/cvs/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/cvs/$id'
    | '/cvs/create'
    | '/companies/'
    | '/cvs/'
    | '/educations/'
    | '/projects/'
    | '/skills/'
    | '/cvs/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvsIdRoute: typeof CvsIdRoute
  CvsCreateRoute: typeof CvsCreateRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  CvsIndexRoute: typeof CvsIndexRoute
  EducationsIndexRoute: typeof EducationsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  CvsIdEditRoute: typeof CvsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educations/': {
      id: '/educations/'
      path: '/educations'
      fullPath: '/educations/'
      preLoaderRoute: typeof EducationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cvs/': {
      id: '/cvs/'
      path: '/cvs'
      fullPath: '/cvs/'
      preLoaderRoute: typeof CvsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cvs/create': {
      id: '/cvs/create'
      path: '/cvs/create'
      fullPath: '/cvs/create'
      preLoaderRoute: typeof CvsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cvs/$id': {
      id: '/cvs/$id'
      path: '/cvs/$id'
      fullPath: '/cvs/$id'
      preLoaderRoute: typeof CvsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cvs/$id_/edit': {
      id: '/cvs/$id_/edit'
      path: '/cvs/$id/edit'
      fullPath: '/cvs/$id/edit'
      preLoaderRoute: typeof CvsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvsIdRoute: CvsIdRoute,
  CvsCreateRoute: CvsCreateRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  CvsIndexRoute: CvsIndexRoute,
  EducationsIndexRoute: EducationsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  CvsIdEditRoute: CvsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
